version: '2'
services:
  web:
    image: docker-tutorial:2.0
    depends_on:
      - app-db
    ports:
      - '8181:8080'
    networks:
    - rede-teste

  app-db:
    image: mongo
    networks:
      rede-teste:
        aliases:
          - app-db

networks:
  rede-teste: