apiVersion: extensions/v1beta1
kind: Deployment                               
metadata:
  name: node
  labels:
    app: node
    env: dev
spec:
  replicas: 1                                           
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: node                                
    spec:
      containers:
        - image: node
          imagePullPolicy: Always                         
          name: node