apiVersion: v1
kind: ReplicationController                                          
metadata:
  name: db
  labels:
    app: db
    env: dev
spec:
  replicas: 1        
  selector:
    app: db
  template:
    metadata:
      labels:
        app: db
        env: db
    spec:
      containers:
        - image: mongo
          name: mongodb