apiVersion: v1
kind: Service          
metadata:
  name: webserver-lb
spec:
  type: LoadBalancer   
  ports:
  - port: 80    
    protocol: TCP      
    targetPort: 8080    
  selector:            
    app: webserver